const generalRules = [
    {'abomination': 'abomination', 'dangerLevel': 0, 'pv': 5, 'rules': 'abomination'},
    {'abomination': 'abomination', 'dangerLevel': 1, 'pv': 7, 'rules': 'abomination'},
    {'abomination': 'abomination', 'dangerLevel': 2, 'pv': 8, 'rules': 'abomination'},
    {'abomination': 'abomination', 'dangerLevel': 3, 'pv': 9, 'rules': 'abomination'},
    {'abomination': 'blob', 'dangerLevel': 0, 'pv': 5, 'rules': 'Blob'},
    {'abomination': 'blob', 'dangerLevel': 1, 'pv': 7, 'rules': 'Blob'},
    {'abomination': 'blob', 'dangerLevel': 2, 'pv': 8, 'rules': 'Blob'},
    {'abomination': 'blob', 'dangerLevel': 3, 'pv': 9, 'rules': 'Blob'},
    {'abomination': 'minotaure', 'dangerLevel': 0, 'pv': 5, 'rules': 'minotaure'},
    {'abomination': 'minotaure', 'dangerLevel': 1, 'pv': 7, 'rules': 'minotaure'},
    {'abomination': 'minotaure', 'dangerLevel': 2, 'pv': 8, 'rules': 'minotaure'},
    {'abomination': 'minotaure', 'dangerLevel': 3, 'pv': 9, 'rules': 'minotaure'},
    {'abomination': 'troll', 'dangerLevel': 0, 'pv': 5, 'rules': 'troll'},
    {'abomination': 'troll', 'dangerLevel': 1, 'pv': 7, 'rules': 'troll'},
    {'abomination': 'troll', 'dangerLevel': 2, 'pv': 8, 'rules': 'troll'},
    {'abomination': 'troll', 'dangerLevel': 3, 'pv': 9, 'rules': 'troll'},
    {'abomination': 'wolf', 'dangerLevel': 0, 'pv': 5, 'rules': 'wolf'},
    {'abomination': 'wolf', 'dangerLevel': 1, 'pv': 7, 'rules': 'wolf'},
    {'abomination': 'wolf', 'dangerLevel': 2, 'pv': 8, 'rules': 'wolf'},
    {'abomination': 'wolf', 'dangerLevel': 3, 'pv': 9, 'rules': 'wolf'},
    {'abomination': 'corrompue', 'dangerLevel': 0, 'pv': 5, 'rules': 'corrompue'},
    {'abomination': 'corrompue', 'dangerLevel': 1, 'pv': 7, 'rules': 'corrompue'},
    {'abomination': 'corrompue', 'dangerLevel': 2, 'pv': 8, 'rules': 'corrompue'},
    {'abomination': 'corrompue', 'dangerLevel': 3, 'pv': 9, 'rules': 'corrompue'}
]