const generalRules = [
    {'abomination': 'abomination', 'dangerLevel': 0, 'pv': 5, 'rules': 'Aucune'},
    {'abomination': 'abomination', 'dangerLevel': 1, 'pv': 7, 'rules': 'Aucune'},
    {'abomination': 'abomination', 'dangerLevel': 2, 'pv': 8, 'rules': 'Aucune'},
    {'abomination': 'abomination', 'dangerLevel': 3, 'pv': 9, 'rules': 'Aucune'},
    {'abomination': 'blob', 'dangerLevel': 0, 'pv': 5, 'rules': 'Aucune'},
    {'abomination': 'blob', 'dangerLevel': 1, 'pv': 7, 'rules': 'Dégats uniquement avec : magie'},
    {'abomination': 'blob', 'dangerLevel': 2, 'pv': 8, 'rules': 'Dégats uniquement avec : magie'},
    {'abomination': 'blob', 'dangerLevel': 3, 'pv': 9, 'rules': 'Dégats uniquement avec : magie; un seul survivant'},
    {'abomination': 'minotaure', 'dangerLevel': 0, 'pv': 5, 'rules': 'Acune'},
    {'abomination': 'minotaure', 'dangerLevel': 1, 'pv': 7, 'rules': 'Dégats uniquement avec : à distance'},
    {'abomination': 'minotaure', 'dangerLevel': 2, 'pv': 8, 'rules': 'Dégats uniquement avec : à distance'},
    {'abomination': 'minotaure', 'dangerLevel': 3, 'pv': 9, 'rules': 'Dégats uniquement avec : à distance; un seul survivant'},
    {'abomination': 'troll', 'dangerLevel': 0, 'pv': 5, 'rules': 'Aucune'},
    {'abomination': 'troll', 'dangerLevel': 1, 'pv': 7, 'rules': 'Dégats uniquement avec : mêlée'},
    {'abomination': 'troll', 'dangerLevel': 2, 'pv': 8, 'rules': 'Dégats uniquement avec : mêlée'},
    {'abomination': 'troll', 'dangerLevel': 3, 'pv': 9, 'rules': 'Dégats uniquement avec : mêlée; un seul survivant'},
    {'abomination': 'wolf', 'dangerLevel': 0, 'pv': 5, 'rules': 'Aucune'},
    {'abomination': 'wolf', 'dangerLevel': 1, 'pv': 7, 'rules': 'Dernier en ordre de priorité'},
    {'abomination': 'wolf', 'dangerLevel': 2, 'pv': 8, 'rules': 'Dernier en ordre de priorité'},
    {'abomination': 'wolf', 'dangerLevel': 3, 'pv': 9, 'rules': 'Dernier en ordre de priorité'},
    {'abomination': 'corrompue', 'dangerLevel': 0, 'pv': 5, 'rules': 'Aucune'},
    {'abomination': 'corrompue', 'dangerLevel': 1, 'pv': 7, 'rules': 'à chaque touche : dégats -1'},
    {'abomination': 'corrompue', 'dangerLevel': 2, 'pv': 8, 'rules': 'à chaque touche : dégats -1'},
    {'abomination': 'corrompue', 'dangerLevel': 3, 'pv': 9, 'rules': 'à chaque touche : dégats -1'}
]